<b> Refresher notes on NumPy </b>

In [2]:
import numpy as np

You need to import the library, you can give this a shorterned name such as <b> np </b>.
You need it installed on the host, e.g. <i>pip install numpy </i>

<b> NumPy Arrays </b>

- There are 2 main types: Vector and matrices
- Vecors are <b> strictly 1-D </b> wheras matrices are <b> 2-D </b>
    - However a matrix can still only have one row or one column

In [1]:
my_list = [1,2,3]

You can create a normal python list and cast it into a numpy array. Below is a version of a <b>1-dimensional</b> array

In [2]:
import numpy as np

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

Below is an example of a <b> 2-dimensional array </b> using a list of lists.

In [6]:
my_mat= [[1,2,3],[4,5,6], [7,8,9]]

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

<i>2 sets of brackes indicates a 2-dimensional array </i>

<b> Most common ways of creating arrays in NumPy </b>
> This works like pythons own range function

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

<b>We can add in a step size too: </b>

In [12]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [13]:
np.zeros(3)

array([0., 0., 0.])

Passes a tuple to create an array of <b> 5 columns and 2 rows </b>

In [16]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

<b> Linspace </b>
Returns evenly spaced numbers over a specified interval
 <i> np.linspace(start, stop, number of points) </i>

In [17]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

<b> Identity Matrix using eye</b>
> Creates a square matrix

In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

<b> RANDOM </b>
> Creating an array of random numbers

<i> this generates a 1-D array </i>

In [20]:
np.random.rand(5)

array([0.60301414, 0.15839413, 0.10183566, 0.71664141, 0.38266295])

<i> this generates a 2-D array </i>

In [22]:
np.random.rand(5,5)

array([[0.64388893, 0.55843876, 0.55644582, 0.04669549, 0.17746183],
       [0.40329114, 0.16802095, 0.58316436, 0.06854954, 0.82846608],
       [0.93545327, 0.00683143, 0.13568572, 0.42281331, 0.92898749],
       [0.85885034, 0.0275311 , 0.28088369, 0.56677665, 0.50291299],
       [0.5431676 , 0.91739853, 0.82501272, 0.7149855 , 0.14647652]])

<b> RANDN </b>
> returns from a normal  distribution centred around 0 rather than 1

In [23]:
np.random.randn(2)

array([-0.53398535, -0.73977159])

In [24]:
np.random.randn(4,4)

array([[ 0.13038427,  0.52055107,  0.18844343,  1.0790408 ],
       [-0.74414412, -0.24861549, -1.68410512, -0.05000609],
       [-0.08204239,  0.52390779,  1.00584101,  0.56402211],
       [-0.15883052,  0.98087651,  1.12596636, -0.14598639]])

<b> RNDINT </b>
> Returns random integers from low to high
    > Low is <b> inclusive </b>
    > High is <b> exclusive </b>

In [26]:
np.random.randint(1,100)

48

We can also specifiy how many random integers we want to be produced

In [28]:
np.random.randint(1,100,5)

array([ 6, 95,  1, 62, 17])

<b> Useful attributes of an array </b>

In [29]:
arr= np.arange(25)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [31]:
ranarr= np.random.randint(0,50,10)

In [32]:
ranarr

array([41, 35, 11, 33, 23, 13,  9, 31, 26,  5])

<b> Reshape method </b>

Returns an array containing the same data with a new shape.

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [33]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

Total size of the array must be unchanged. Rows multiplied by columns must be the same amount of elements in the OG one

<b>Max, Min, Index </b>

In [35]:
ranarr.max()

41

In [36]:
ranarr.min()

5

In [37]:
ranarr

array([41, 35, 11, 33, 23, 13,  9, 31, 26,  5])

In [38]:
ranarr.argmax()

0

In [39]:
ranarr.argmin()

9

<b> Shape of a vector </b>

In [41]:
arr.shape

(25,)

The above shows that it's <b> 1-dimensional </b>

In [42]:
arr= arr.reshape(5,5)

In [43]:
arr.shape

(5, 5)

The above shows that it's <b> 2-dimensional </b>

<b> DTYPE </b>
stype shows the data type

In [46]:
arr.dtype

dtype('int64')

In [47]:
from numpy.random import randint

In [48]:
randint(2,10)

6