# NumPy Indexing and Selection

In [1]:
import numpy as np

In [2]:
arr= np.arange(0,11)

In [7]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
arr[8]

8

You can also use <b>slice:</b>
(in a similar way to python)

In [4]:
arr[1:5]

array([1, 2, 3, 4])

In [5]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [6]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [8]:
arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [9]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

NumPy arrays differ from python arrays due to their ability to <b> broadcast </b>

In [10]:
arr[0:5] = 100

In [11]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [19]:
arr= np.arange(0,11)

In [13]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
slice_of_arr= arr[0:6]

In [15]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [16]:
slice_of_arr[:]=99

In [17]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [18]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Data is not copied, it's a view of the original array! This avoids memory problems!

This happens as you are changing a <b> slice of the array </b>
To avoid this you need to explicitley state that you want a <b> copy of the array</b>.
Changes made to this <b>copy</b> won't affect the original array

In [20]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
arr_copy= arr.copy()

In [23]:
arr_copy[:]=100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Indexing a 2-Dimensional array/ <b>matrix</b>

In [25]:
arr_2d= np.array([[5,10,15],[20,25,30],[35,40,45]])

In [26]:
arr_2d


array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

2 ways of grabbing from a 2-d array: 
- Single bracket format (betetr for use )
- Double bracket format

<b>Double Bracket format: </b>

In [27]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [28]:
arr_2d[0][0]

5

This will grab the item on <b> row 1,column 1 </b> 

In [29]:
arr_2d[0]

array([ 5, 10, 15])

In [31]:
arr_2d[2][1]

40

In [32]:
arr_2d[2,1]

40

<b>To get chunks rather than elements: </b>
(we can us slice notation)

In [33]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [37]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

This means grab everything from 0 to 2

To grab from 0 to 2, everything onwards from index 1

In [36]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [39]:
arr_2d[:1,2:]

array([[15]])

<b>More we can do: </b>
Running comparision operator on an array creates a boolean array

In [49]:
arr=np.arange(1,11)

In [50]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
bool_arr= arr >5

In [52]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

The code above runs a comparison operator on the array, if each element is >5 it's marked true, if not it's false

From this <b> Boolean Array </b> we can index/conditionaly select items that were true from the original array <b> see below </b>

In [54]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

normally you would do this all in <b> one-step </b>:

In [55]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

If we want to know all the elements of the array that are <b>less than three:</b>

In [56]:
arr[arr<3]

array([1, 2])

<b>Review</b>

In [57]:
arr_2d= np.arange(50).reshape(5,10)

In [63]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [65]:
arr_2d[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [64]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])